name: Build LSA Whisperer
on:
  workflow_dispatch: # Allows you to manually run the workflow
  push: # Run when code changes
    branches: ['v3.0']
    paths: ['cmake/**', 'include/**', 'libraries/**', 'source/**', 'CMakeList.txt']
jobs:
  build:
    runs-on: windows-latest
    outputs:
      artifact: lsa-whisperer-${{ steps.ghd.outputs.describe }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Prepare the build
      run: cmake .. -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0
      working-directory: builds
    - name: Run the build
      run: cmake --build .
      working-directory: builds
    - name: Generate description for artifact name
      id: ghd
      uses: proudust/gh-describe@v2
      with:
        match: v*
    - name: Upload artifact to workflow run
      uses: actions/upload-artifact@v4
      with:
        name: lsa-whisperer-${{ steps.ghd.outputs.describe }}
        path: builds/Debug/**
