name: Build LSA Whisperer
on:
  workflow_dispatch: # Allows you to manually run the workflow
  push:
    branches: ['master']
    paths: ['bofs/**', 'cmake/**', 'include/**', 'libraries/**', 'lwdk/**', 'modules/**', 'source/**', 'CMakeList.txt']
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Prepare Python
      id: prepare_python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Prepare Python dependencies
      run: ${{ steps.prepare_python.outputs.python-path }} -m pip install -r requirements.txt
    - name: Prepare the build
      run: cmake .. -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0
      working-directory: builds
    - name: Run the build
      run: cmake --build .
      working-directory: builds
    - name: Generate description for artifact name
      id: ghd
      uses: proudust/gh-describe@v2
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: lsa-whisperer-${{ steps.ghd.outputs.describe }}
        path: builds/Debug/**

